### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by prapt179** [hpe-idol/find#34]
The favicon appears only on the login page using IE 11.  Is this a local issue or are others experiencing the same thing?

**Comment by tung-jin-chew-hp** [comment]
Works for me in Firefox and Chrome; at least in the latest version.

![image](https://user-images.githubusercontent.com/7871081/30059232-27417ba6-9236-11e7-883c-03fbc49808b4.png)

![image](https://user-images.githubusercontent.com/7871081/30059253-3d1a9e58-9236-11e7-95f3-37ebd7e82def.png)
