### ISSUE TITLE
dev branch does not show search box

### ISSUE THREAD

**Issue by samirOs** [hpe-idol/find#5]
I like the recent enhancements in find dev branch, but for some reason the search box is cleared, you can input anything. 

this is the branch am using. 
commit b33d36b5c79907cc9d5b531fd4123e32877dd2ba
Author: Matthew Gordon <matthew.gordon2@hpe.com>
Date:   Wed Oct 12 17:58:49 2016 +0100

**Comment by maheshkumarrp** [comment]
My understanding is if the logged in user's role is  **FindBI** role then search box will not be present and 
if the logged in user's role is  **FindUser** role then search box will be present

**Comment by brian-beckett-hpe** [comment]
Mahesh is correct - the BI user searches in a different way that the standard search user.  Instead of the search bar, we have a concept search box in the sidebar.
