### ISSUE TITLE
Suggest amend run parameter ordering in Running-a-Production-Copy-of-Find.md

### ISSUE THREAD

**Issue by djpidol** [hpe-idol/find#6]
Issue observed with:

Maven home: C:\apache-maven-3.3.9
Java version: 1.8.0_102, vendor: Oracle Corporation

when running using:

java -jar find.war -Dhp.find.home=&lt;path_to_find_home_directory&gt;

fails due to:

java.lang.IllegalStateException: No configuration file defined. System property key: hp.find.home

reversing parameter order solved this on my platform

java -Dhp.find.home=&lt;path_to_find_home_directory&gt; -jar find.war

**Comment by tung-jin-chew-hp** [comment]
Thanks, Alex has fixed that on
  https://github.com/hpe-idol/find/wiki/Running-a-Production-Copy-of-Find/_compare/a8521bee7a8ff695f086853d771c119099d1095a...ddb05ac198832007a9f44f689acedec5f50a7b73
